version: '3'

services:
  nodejs:
    env_file:
      - .env.development
    
    container_name: nodejs
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    env_file:
      - .env.development
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

      